name = "hono-sandbox"
main = "src/index.ts"
compatibility_date = "2025-01-21"
compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

[[kv_namespaces]]
binding = "CloudflareAuthKV"
id = "f40acac8f36e4c359963be79d6d245c1"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

[observability]
enabled = true
# head_sampling_rate = 1